#!/usr/bin/env bash

# based on : aur-search (MIT License) https://github.com/takiz/aur-search

nbrowser_bang(){
  aur_jsondata=$(curl "https://aur.archlinux.org/rpc/" -s \
                       -G --data-urlencode "v=5" \
                       -G --data-urlencode "type=search" \
                       -G --data-urlencode "arg=$*" \
                       -H "user-agent:Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0" \
                       -H "accept-language:en-US, en;q=0.9" \
                       -H "accept-encoding:gzip" --compressed \
                )

  ERR=$(echo "$aur_jsondata" | jq -r '.error')

  if [ "$ERR" != "null" ]; then
    _pemx $ERR
  fi

  aur_itemid=$(printf '%s' "$aur_jsondata" | jq -r '.results | .[] | .Name + "|" + .Version + "|" + .Description' | column -t -s '|'\
             | _choose | awk '{print $1}' )

  [ -z "$aur_itemid" ] && exit 1

  url_handler "https://aur.archlinux.org/packages/$aur_itemid"
}
