#!/usr/bin/env bash

nbrowser_bang(){
  # check if googler installed in your system
  has 'googler' || _pemx "'googler' is no installed in your system!"
  has 'jq' || _pemx "'jq' is no installed in your system!"
  # search for query $@ using googler and get result in json format
  ggl_result_json=$(googler --count=25 --json "$@")
  # parse results with jq and show a menu to let the user choose,
  # then extract the url from selected line using awk
  ggl_result_url=$(printf '%s' "${ggl_result_json}" | jq -r '.[]| "\(.title)  --  \(.url)"' \
                 | _choose | awk '{print $NF}' )
  # if no result has been selected exit
  [ -z "$ggl_result_url" ] && exit 0
  # open selected URL
  url_handler "$ggl_result_url"
}
