#!/usr/bin/env bash

nbrowser_bang() {
  has 'qrencode' || _pemx "'qrencode' is no installed in your system!"

  [ -z "$*" ] && local QUERY=$(_input "QR Generator") || local QUERY="$*"
  [ -z "$QUERY" ] && exit 0

  qrencode "$QUERY" -o /tmp/qr -s 20 && sxiv -b /tmp/qr
  rm /tmp/qr
}
